--
-- require("lazy.core.config").plugins # get the plugins
--    local stats = require("lazy").stats()
-- local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
-- dashboard.section.footer.val = "⚡ Neovim loaded " .. stats.count .. " plugins in " .. ms .. "ms"
-- pcall(vim.cmd.AlphaRedraw)
